version: 2.1

jobs:
  ant-build-and-test:
    working_directory: ~/Interpreter-APO
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: APT Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-17-jdk
      - run:
          name: APT Install Apache ANT
          command: sudo apt-get update && sudo apt-get install ant
      - run:
          name: Install JUnit5 for ANT
          command: ./ci/install_ant_junit5.sh
      - run:
          name: Download Dependencies
          command: ant resolve
      - run:
          name: Build
          command: ant jar
      - run:
          name: Test
          command: ant test
      - store_test_results:
          path: ./antBuild/junit/result
  gradle-build-and-test:
    working_directory: ~/Interpreter-APO
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: APT Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-17-jdk
      - run:
          name: Build
          command: ./gradlew jar
      - run:
          name: Test
          command: ./gradlew test
      - store_test_results:
          path: ./build/test-results/test

workflows:
  main:
    jobs:
      - ant-build-and-test
      - gradle-build-and-test
