name: GitHub Actions

on: [ push, pull_request ]

jobs:
  gradle-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: APT Install Java
        run: |
          sudo apt-get update && sudo apt-get install openjdk-17-jdk
          sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
      - name: Build
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          ./gradlew jar
      - name: Test
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          ./gradlew test
